Crd install bugfix
rancher/prometheus-federator pull request #114
Opened 2024-10-24 21:27 UTC by mallardduck

Related Issue: 

### Checklist

Please fill out this table to identify which fields need to be modified in your PR.

**Under `Status`, either indicate `Does Not Apply` or `Added to this PR`**.

| **Version to be incremented**                                              | Why should this be modified?                                                                                                           | Status                                      |
|-----------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------|
| `version` in rancher-project-monitoring `package.yaml`                  | You modified the contents of the `rancher-project-monitoring` chart to make changes                                                    |  |
| `helmProjectOperator.image.tag` in prometheus-federator `values.yaml` | Either you modified the rancher-project-monitoring chart or you modified the `main.go` file                                          |  |
| `appVersion` in prometheus-federator `Chart.yaml`                     | You modified the `helmProjectOperator.image.tag` in the above box                                                                      |  |
| `version` in prometheus-federator `Chart.yaml`                        | Either you modified the `appVersion` in the above box or you modified the contents of the `prometheus-federator` chart to make changes |  |

2024-10-28 15:26 UTC, mallardduck commented
So with this fix in place, if you create a cluster (using k3s/rke2) and then later install the chart you should see CRDs with 2 sets of timestamps. One for the cluster creation and one for the helm chart install time - the `helmcharts` and `helmchartconfigs` will be from creation time. Like:

```
helmchartconfigs.helm.cattle.io                                   2024-10-28T00:53:16Z
helmcharts.helm.cattle.io                                         2024-10-28T00:53:16Z
helmreleases.helm.cattle.io                                       2024-10-28T15:23:18Z
projecthelmcharts.helm.cattle.io                                  2024-10-28T15:23:18Z
```

2024-10-29 15:44 UTC, mallardduck commented
Summary of Helm-Controller Situation:

| Helm Controller | Release Date | CRD Changes (Compared to Current) | RKE2                                                                              | K3S                                                                    | PromFed | PromFed Update Safety |
|-----------------|--------------|-----------------------------------|-----------------------------------------------------------------------------------|------------------------------------------------------------------------|---------|-----------------------|
| v0.13.1         | Nov 23, 2022 | N/A                               | v1.26.1+rke2r1, v1.25.6+rke2r1                                                    | v1.26.3+k3s1,  v1.25.8+k3s1                                            | Current | N/A                   |
| v0.13.3         | Apr 4, 2023  | False                             | N/A                                                                               | v1.27.1+k3s1, v1.26.4+k3s1, v1.25.9+k3s1                               | N/A     | V Low Risk            |
| v0.14.0         | May 10, 2023 | True                              | (skipped, not helpful info)                                                       | (skipped, not helpful info)                                            | N/A     | Higher Risk           |
| v0.15.4         | Aug 15, 2023 | True                              | v1.29.4+rke2r1, v1.28.9+rke2r1, v1.27.13+rke2r1, v1.26.12+rke2r1, v1.25.16+rke2r2 | v1.29.0+k3s1, v1.28.5+k3s1, v1.27.9+k3s1, v1.26.12+k3s1, v1.25.16+k3s4 | N/A     | Higher Risk           |
| v0.16.4         | Sep 5, 2024  | True; even more                   | v1.30.5+rke2r1                                                                    | v1.30.5+k3s1                                                           | N/A     | V High Risk           |

Note that I've been testing with 1.28.14 which matches up with `v0.15.13` of helm-controller. And as noted in the table, `v0.13.1` of helm-controller currently lines up with the one PromFed ships.

More info on CRD differences: https://gist.github.com/mallardduck/120b1d5d833126ae2cb8ff2df20c53c5

2024-12-11 20:26 UTC, alexandreLamarre requested changes

2024-12-11 20:26 UTC, alexandreLamarre commented on pkg/helm-project-operator/controllers/common/operator.go
> +	DetectK3sRke2 bool
Having instance detection logic is tricky and subject to change, I'd rather avoid this... 

Instead is there a deterministic way to check resource ownership of the helm-controller-crds? as this wouldn't have the problem of being tied to instance specific node settings

2024-12-11 20:26 UTC, alexandreLamarre commented on pkg/helm-project-operator/controllers/common/operator.go
> +	DetectK3sRke2 bool
Alternatively, there may be an SDK for this already in frameworks to detect this stuff - having split definitions for instance detection across products is usually a bad idea

2024-12-11 21:02 UTC, mallardduck commented on pkg/helm-project-operator/controllers/common/operator.go
> +	DetectK3sRke2 bool
@alexandreLamarre - Totally agreed that other methods would be preferable. However in my prior research I was unable to find a better method to directly query "What controller/chart owns this CRD". As ideally we could rely on information directly associated with the CRD in question.

For a more proper solution to the CRD aspects, I will create an issue to start a discussion with a larger group of Frameworks+O&B folks. Additionally, I will tweak this implementation to ensure it better respects back/fore-ward compatibility better.

This way we can provide a bandaid patch to solve this sooner without that causing new issues later when we implement the proper solution.

2024-12-11 22:49 UTC, mallardduck commented on pkg/helm-project-operator/controllers/common/operator.go
> +	DetectK3sRke2 bool
Created issue for tacking here: https://github.com/rancher/rancher/issues/48393

2024-12-12 19:58 UTC, alexandreLamarre requested changes
The other thing we need to start doing is adding behavioral tests in Go for every code change, establishing clear expected behavior in something other than just documentation and having CI catch it.

This PR should include those tests as well and I'm happy to sync up about those.

2024-12-12 19:58 UTC, alexandreLamarre commented on pkg/helm-project-operator/crd/crds.go
> +	return k8sRuntimeType, nil
Going back up to the previous discussion, if we can't detect owners of crds from other methods, then we shouldn't have auto detect logic at all.

It can introduce many incompatibilities across many versions - does it work on older rke2 and k3s versions? will it work going forward? How will we use a test matrix to ensure it always works? It's what we call an out of band dependency and those should generally be avoided if possible, because they introduce unnecessary complexity both in code and in this instance especially in testing. 

I'm almost certain that's also why the original controller has a toggle to use an embedded controller or not, rather than detect specific instances. In this case, I'd heavily consider a toggle to just filter CRD updates and omit detection logic altogether.

2024-12-12 20:45 UTC, alexandreLamarre approved these changes

2024-12-12 20:57 UTC, alexandreLamarre approved these changes
Agreed to leave auto detection as an experimental feature and to omit tests to move it to prod asap

2024-12-12 21:20 UTC, mallardduck commented on pkg/helm-project-operator/experimental/runtime.go
> +// Deprecated: This feature is a stop gap not expected to be maintained long-term.
Figured we just go for it and deprecate from day 1 even tho it feels weird.

Big picture it feels better since it's a clear signal that this method isn't intended to be used long term. Nor something that needs to be maintained once a better mechanism to get the same information is in place.

2024-12-12 21:20 UTC, mallardduck commented on packages/prometheus-federator/charts/values.yaml
> +    # !! EXPERIMENTAL OPTION !! - Use this feature with caution and careful consideration.
Similarly warn end-users that this value is experimental and to use with care. Ultimately we added it in a way that won't cause issues if we eventually remove it, or even if customers use unexpected combinations of PromFed chart and PromFed images.

2024-12-12 21:20 UTC, mallardduck commented on pkg/helm-project-operator/crd/crds.go
> +	// TODO: The underlying crd.CRD is deprectated and will eventually be removed
Leave future TODO to remind us that this `crd.CRD` is deprecated.

2024-12-12 21:20 UTC, mallardduck commented on pkg/helm-project-operator/crd/crds.go
> +	// TODO: In the future, this should not rely on detecting k8s runtime type
Finally very clear todo here, to make it even more clear this will be removed in the future.

2024-12-13 14:05 UTC, merged