Update prometheus-federator to use dependencies from k8s 1.30+
rancher/prometheus-federator pull request #141
Opened 2024-12-27 23:29 UTC by alexandreLamarre

Related Issue: 

### Checklist

Please fill out this table to identify which fields need to be modified in your PR.

**Under `Status`, either indicate `Does Not Apply` or `Added to this PR`**.

| **Version to be incremented**                                              | Why should this be modified?                                                                                                           | Status                                      |
|-----------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------|
| `version` in rancher-project-monitoring `package.yaml`                  | You modified the contents of the `rancher-project-monitoring` chart to make changes                                                    |  |
| `helmProjectOperator.image.tag` in prometheus-federator `values.yaml` | Either you modified the rancher-project-monitoring chart or you modified the `main.go` file                                          |  |
| `appVersion` in prometheus-federator `Chart.yaml`                     | You modified the `helmProjectOperator.image.tag` in the above box                                                                      |  |
| `version` in prometheus-federator `Chart.yaml`                        | Either you modified the `appVersion` in the above box or you modified the contents of the `prometheus-federator` chart to make changes |  |

2025-01-07 17:45 UTC, alexandreLamarre commented on cmd/prometheus-federator/main.go
> +	managedCRDs := common.ManagedCRDsFromRuntime(f.RuntimeOptions)
I simplified the management of CRDs here by reading from the runtime configuration file.

- We manage (aka update) helm-locker CRDs IFF we are running an embedded helm-locker
- We manage (aka update) helm-controller CRDs IFF we are running an embedded helm-controller

IMO this was an oversight from the original maintainers of the operator, that they blindly redeployed all CRDs even if we weren't running the matching embedded controller

2025-01-07 17:49 UTC, alexandreLamarre commented on cmd/prometheus-federator/main.go
> +	managedCRDs := common.ManagedCRDsFromRuntime(f.RuntimeOptions)
We can extend the tracker abstraction to customize the CRD objects before they are created, but I didn't see a need to do this yet, it becomes messy if there needs to be breaking changes to what fields indicate is being managed by us or someone else

2025-01-14 15:43 UTC, alexandreLamarre commented on pkg/chart/data.go
> +}
Intentionally making this public in a public package so we can import a specific version of prometheus-federator and see the charts vendored within it. 

It doesn't impact the immutability of the charts build into the binary, but allows alternate visibility into what chart is built into what commit of prometheus federator without having to deploy an image.

I'm open to reverting this improvement since it isn't necessary but though it might be a useful change long term.

2025-01-14 15:45 UTC, alexandreLamarre commented on pkg/chart/build/rancher-project-monitoring.tgz.base64
See `pkg/chart/data.go`, but I think the overhead of ~12Kb files with hopefully small diffs aside from major version bumps of project-monitoring should not impact the usual git operations too much based on my experience...

Especially since we plan on removing the chart hosting to a separate repository, I think the net impact will still be negative on the size/ amount of objects managed by git

2025-01-14 19:58 UTC, alexandreLamarre commented on scripts/package-helm
> +
Not 100% about this, but I believe it is better to edit the version values of the embedded helm-charts before building the images (in a separate commit/PR) for clarity. 

The prometheus-federator chart itself can have sed/perl auto-inject versions when building though, that I don't mind

2025-01-14 19:58 UTC, alexandreLamarre commented on scripts/build-chart
> +  # edit-charts "build/charts/${CHART}/Chart.yaml" "${HELM_CHART_VERSION}" "${HELM_IMAGE_TAG}"
Not 100% about this, but I believe it is better to edit the version values of the embedded helm-charts before building the images (in a separate commit/PR) for clarity. 

The prometheus-federator chart itself can have sed/perl auto-inject versions when building though, that I don't mind

2025-01-15 15:58 UTC, mallardduck commented on cmd/prometheus-federator/main.go
> +	managedCRDs := common.ManagedCRDsFromRuntime(f.RuntimeOptions)
My only major concern with the summary provided is, if I'm a user who:

- Wants to enable PromFeds `helm-controller`, but
- NOT have prom-fed manage the CRDs

Is that still possible? Or are we drawing a line in the sand with this PR, so if you use PromFeds helm-controller then PromFed will always do the CRDs? In result, for k3s/rke2 users they should always disable `helm-controller`?

I understand that doing this makes our compatibility story much more simple. So that's fine if that's the case, we just need to make sure that's clear in release notes (and values.yaml descriptions) probably.

2025-01-15 16:02 UTC, mallardduck commented on cmd/prometheus-federator/main.go
> +	managedCRDs := common.ManagedCRDsFromRuntime(f.RuntimeOptions)
I suspect it's probably rare that customers have multiple `helm-controllers` for necessary performance reasons. So maybe it's not a big deal to eliminate the option to use the PromFed `helm-controller` in an environment where another one exists?

And even then, maybe the correct solution is that customers with `helm-controller` external to PromFed needing 2, should just run 2 external ones of the same version.

Since that's much more simple than having to consider a crazy huge compatabiity matrix of what versions of PromFed work with what versions of `helm-controller` (and there by versions of k3s/rke2).

2025-01-15 16:07 UTC, mallardduck commented on pkg/chart/build/rancher-project-monitoring.tgz.base64
Ehh. I'll have to digest this for a bit. My instinct is that I'll probably revert this with chart-split PR anyway. But maybe I can find a mental model where this makes sense.

Big picture the expectation we should have with `rancher-project-monitring` is that anytime `rancher-monitoring` changes, then `rancher-porject-monitoring` will automatically be changing too.

And if we ship `rancher-monitoring` we should also be shipping PromFed+RPM at the same cycle. This way we directly eliminate the lag between the two which causes us to use a mixture of images and generally skews CVE numbers.

2025-01-15 16:20 UTC, mallardduck requested changes

2025-01-15 16:20 UTC, mallardduck commented on go.mod
> +go 1.23.3
Can this be `1.23.0`?

2025-01-15 16:20 UTC, mallardduck commented on go.mod
> +	github.com/rancher/wrangler/v3 v3.2.0-rc.1
Oh right, this needs to use `rc.2` and the go version thing will go back to `.0`

2025-01-15 17:17 UTC, alexandreLamarre commented on cmd/prometheus-federator/main.go
> +	managedCRDs := common.ManagedCRDsFromRuntime(f.RuntimeOptions)
Having multiple helm-controllers is not supported, its a singleton and running multiple leads to race conditions over ownership by different helm-controller instances.

2025-01-15 17:21 UTC, alexandreLamarre commented on internal/helm-project-operator/pkg/controllers/controllers.go
> +			"6443",
Also bumping the embedded helm controller requires a reference to the api server port. Since the embedded helm-controller runs within k3s it has access to the apiserver port on localhost. I doubt it works as intended when its run embedded and I didn't have the bandwidth to test that.

2025-01-15 17:24 UTC, alexandreLamarre commented on pkg/chart/build/rancher-project-monitoring.tgz.base64
When shipping an image or application logic it is more useful to see and stage the diffs and manually update them or open an automation PR with the diffs visible

Having the go:embed files ignored is bad practice IMO

2025-01-15 17:26 UTC, alexandreLamarre commented on cmd/prometheus-federator/main.go
> +	managedCRDs := common.ManagedCRDsFromRuntime(f.RuntimeOptions)
>>>My only major concern with the summary provided is, if I'm a user who:

>>>    Wants to enable PromFeds helm-controller, but
>>>    NOT have prom-fed manage the CRDs

It's possible but inherently unsafe and not a good idea, but users can still do it via the crdManagement flags

2025-01-15 17:28 UTC, alexandreLamarre commented on pkg/chart/build/rancher-project-monitoring.tgz.base64
Also I don't think automation will ever get to the point where rebasing monitoring will out of the box rebase project-monitoring since the resources tend to change alot between 5-10 versions

2025-01-15 17:30 UTC, alexandreLamarre commented on pkg/chart/build/rancher-project-monitoring.tgz.base64
(The point of this is not to get in the way of any chart build or automation improvements but to have clear tracking of what gets built into the applications)

2025-01-15 17:31 UTC, alexandreLamarre commented on go.mod
> +go 1.23.3
I think not with wrangler as it currently stands, let me check

2025-01-15 17:34 UTC, alexandreLamarre commented on go.mod
> +go 1.23.3
We can circle back to this when wrangler is un-rc'ed I think, I don't think it's high priority

2025-01-15 17:37 UTC, mallardduck commented on go.mod
> +go 1.23.3
Yeah, bump to wangler rc.2 will fix..I worked with them to fix for BRO

2025-01-15 17:39 UTC, mallardduck commented on cmd/prometheus-federator/main.go
> +	managedCRDs := common.ManagedCRDsFromRuntime(f.RuntimeOptions)
> Having multiple helm-controllers is not supported, its a singleton and running multiple leads to race conditions over ownership by different helm-controller instances.

This hasn't been true for a while actually. They can coexist just fine.

2025-01-15 17:48 UTC, mallardduck commented on go.mod
> +	github.com/k3s-io/helm-controller v0.16.6-0.20241210112214-b40937ee695b
This should probably be [v0.16.5](https://github.com/k3s-io/helm-controller/releases/tag/v0.16.5) as that matches the version used by the stable release of k8s 1.32 for k3s/rke2.

2025-01-15 22:35 UTC, alexandreLamarre commented on cmd/prometheus-federator/main.go
> +	managedCRDs := common.ManagedCRDsFromRuntime(f.RuntimeOptions)
The managed-by annotation doesn't work as you would think it does -- whichever helm controller picks up the object first controls the object but it was never fleshed out beyond hardening currently picked up resources

2025-01-15 22:36 UTC, alexandreLamarre commented on cmd/prometheus-federator/main.go
> +	managedCRDs := common.ManagedCRDsFromRuntime(f.RuntimeOptions)
I believe that annotation was a stepping stone towards allowing for concurrent helm-controllers/ helm-lockers / helm-project-operators but you can set up some tests to see it won't behave consistently

2025-01-15 23:08 UTC, mallardduck commented
BTW - I just realized that since this is targeting 1.32 we should ideally wait to ship this along with Rancher 2.11 that officially supports 2.11. And we're using RC libraries intended for Rancher 2.11 which feels wrong to include this soon. Because we don't do branching right now we can't merge this into main and expect it to not affect the February release cycle.

So what if you changed this to target 1.31 and Rancher 2.10 based libraries that way it doesn't have to be something we only do in 2.11. Otherwise we have to some how implement branch strategy and do partial reverts before the February release cycle.

2025-01-15 23:45 UTC, mallardduck commented on cmd/prometheus-federator/main.go
> +	managedCRDs := common.ManagedCRDsFromRuntime(f.RuntimeOptions)
🤔 Yeah I have studied the code and tested it many times so I'm confused about the disconnect. Maybe it would help if we pair on this tomorrow and I can show how it works in my lab. As far as proving this via testing, I didn't think that was the scope of the discussion. I'm open to us trying to cover that in e2e testing...but also feels tangential to my current point.

2025-01-16 17:10 UTC, mallardduck commented on cmd/prometheus-federator/main.go
> +	managedCRDs := common.ManagedCRDsFromRuntime(f.RuntimeOptions)
Ohh - I may see where I'm confused now. The ground work is there but the locks may be blocking that functionality. I'll sync up with @jbiers on this to see what we can sort out.

2025-01-20 13:42 UTC, alexandreLamarre commented
@mallardduck The intention was always to bump dependencies as aggressively as possible and branch off the main branch, and downgrade dependencies selectively

2025-01-20 13:47 UTC, alexandreLamarre commented on cmd/prometheus-federator/main.go
> +	managedCRDs := common.ManagedCRDsFromRuntime(f.RuntimeOptions)
We really don't want to make it a non-singleton since `rancher-monitoring` is a singleton, and its companion app `prometheus-federator` is also a singleton

Users have been using it in this manner for a while, and the edge cases where we want a non-singleton are only clear to me if we use the underlying helm-project-operator to support multiple charts which is IMO not likely to happen at all since it isn't flexible and the tenancy around projects and specifically the helm-project-operator is hacky at best

2025-01-21 14:51 UTC, mallardduck commented
@alexandreLamarre - I guess that wasn't super clear. Either way works in the end I guess.

However after merging this we need to be careful about what tag is used to test main. If `main` needs to match rancher `main`, then that means the tag needs to logically match that version and leave a gaps. That way we have either a major/minor that correlates to the Rancher version, but versions under it that we can use to fill in gaps later.

i.e. After merging this the tag for main becomes `6.x` by default, and covers 2.11; so in turn 5.x is for 2.10 and so on.

I think my misunderstanding there also may mean my opinion in change ordering will be different here. Specifically I think we do need to sort out my effort to split charts+image code first. Since having that complete will make us more prepared for the branching once implemented here.

2025-01-29 16:39 UTC, alexandreLamarre commented on pkg/chart/data.go
> +}
I'm going to revert this

2025-01-29 17:31 UTC, alexandreLamarre commented on pkg/chart/build/rancher-project-monitoring.tgz.base64
Reverted this change

2025-01-30 23:25 UTC, mallardduck requested changes

2025-01-30 23:25 UTC, mallardduck commented on charts/prometheus-federator/values.yaml
> +        tag: v0.9.3-build20241008
Think that `rancher/klipper-helm:v0.9.4-build20250113` will match the helm-controller we're targeting with this branch.

2025-01-30 23:25 UTC, mallardduck commented on cmd/prometheus-federator/main.go
> +	// and always disable helm controller crd management since the cluster-scoped one should always manage those
This part may want to be removed and let users control it.

I'm worried that, if:

- User disabled k3s/rke2 `helm-controller` and
- User has namespace `helm-controller` mode setup, and
- user has `DETECT_K3S_RKE2=true` - because one of the namespace ones owns CRDs,
- user manually set `helmController.enabled=true` to PromFed be the controller

This change will create a breaking change - maybe that's fine but at the very least we need to document/Release Note it for users in that situation to know:
- They should also deploy a `helm-controller` in namespaced mode to cover PromFed too.

2025-01-30 23:25 UTC, mallardduck commented on cmd/prometheus-federator/main.go
> +	// and always disable helm controller crd management since the cluster-scoped one should always manage those
Maybe I'm just confused about the wording of the second line comment here?

2025-01-31 16:01 UTC, alexandreLamarre commented on cmd/prometheus-federator/main.go
> +	// and always disable helm controller crd management since the cluster-scoped one should always manage those
I can double check but I'm fairly certain this matches 1-1 the existing control flow in main. 

I also want to double check when we say namespaced helm-controller we mean one that watches all namespaces but has the controller-name set to something prometheus federator specific -- since the embedded helm-controller expects to watch across arbitrary namespaces

2025-01-31 16:04 UTC, alexandreLamarre commented on cmd/prometheus-federator/main.go
> +	// and always disable helm controller crd management since the cluster-scoped one should always manage those
https://github.com/rancher/prometheus-federator/blob/57444baf7cdad144dc308af0152bf02e8e1ad90e/internal/helm-project-operator/crd/crds.go#L267-L272

Every time we attempt to create crds in main we do, which automatically disables helm-controller crds

https://github.com/rancher/prometheus-federator/blob/57444baf7cdad144dc308af0152bf02e8e1ad90e/internal/helm-project-operator/crd/crds.go#L204-L206

2025-01-31 16:06 UTC, alexandreLamarre commented on cmd/prometheus-federator/main.go
> +	// and always disable helm controller crd management since the cluster-scoped one should always manage those
Note that here, in the shared CRD abstraction : 
https://github.com/rancher/prometheus-federator/blob/22072cd6eb981b26c97d212dd92e8430da506024/cmd/prometheus-federator/main.go#L94-L97

We don't actually disable the helm-controller (since we're not overwriting the config passed to the operator), we just tell the crd tracker to not track crds related to helm-controller, so users can still have the embedded helm-controller running, but not manage the crds in prom-fed

2025-01-31 17:17 UTC, mallardduck commented on cmd/prometheus-federator/main.go
> +	// and always disable helm controller crd management since the cluster-scoped one should always manage those
> when we say namespaced helm-controller
Oh - sorry that's right I had a brain fart. The PromFed embedded helm-controller would be a second instance of a "global controller" since it's listening for all namespaces - but only for charts designated to be managed by it.

Where as if they opt to disable the PromFed provided controller then to be compliant with `helm-controller` policy and still keep PromFed working, the must:
a) use a global controller (either embedded in k3s/rke2, or added to any k8s), OR
b) use namespaced controller(s) so that each namespace they use for PromFed are covered.

2025-01-31 17:19 UTC, mallardduck commented on cmd/prometheus-federator/main.go
> +	// and always disable helm controller crd management since the cluster-scoped one should always manage those
So yeah - I think we're good and I was confused by the wording initially. I don't have any proposed changes to fix the wording - I probably just needed to read it slower 😆

2025-02-13 20:02 UTC, mallardduck approved these changes

2025-02-21 16:03 UTC, jbiers approved these changes

2025-02-26 14:58 UTC, merged