Update prometheus federator app version to 0.3.5 / charts to 0.4.1
rancher/prometheus-federator pull request #81
Opened 2023-12-14 19:12 UTC by alexandreLamarre

Related Issue: 

### Checklist

Please fill out this table to identify which fields need to be modified in your PR.

**Under `Status`, either indicate `Does Not Apply` or `Added to this PR`**.

| **Version to be incremented**                                              | Why should this be modified?                                                                                                           | Status                                      |
|-----------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------|
| `version` in rancher-project-monitoring `package.yaml`                  | You modified the contents of the `rancher-project-monitoring` chart to make changes                                                    | Added in this PR  |
| `helmProjectOperator.image.tag` in prometheus-federator `values.yaml` | Either you modified the rancher-project-monitoring chart or you modified the `main.go` file                                          | Does Not Apply |
| `appVersion` in prometheus-federator `Chart.yaml`                     | You modified the `helmProjectOperator.image.tag` in the above box                                                                      | Added in this PR |
| `version` in prometheus-federator `Chart.yaml`                        | Either you modified the `appVersion` in the above box or you modified the contents of the `prometheus-federator` chart to make changes | Added in this PR |

2023-12-14 19:20 UTC, joshmeranda commented on packages/prometheus-federator/charts/values.yaml
> +    tag: v0.3.5
I don't think this tag exists?

2023-12-14 19:22 UTC, joshmeranda commented on packages/prometheus-federator/charts/Chart.yaml
> +appVersion: 0.3.5
we aren't changing anything in the actual federator so this should stay the same.

2023-12-14 19:23 UTC, joshmeranda requested changes
See comments, just a versioning issue

2023-12-14 19:43 UTC, alexandreLamarre commented on packages/prometheus-federator/charts/Chart.yaml
> +appVersion: 0.3.5
We have to change this to build the new image with go 1.20

2023-12-14 19:47 UTC, alexandreLamarre commented on packages/prometheus-federator/charts/values.yaml
> +    tag: v0.3.5
In the docs it mentions adding the git tag after a PR is merged, which didn't seem right but looking at how the automation works it seems that its fine

2023-12-14 19:48 UTC, joshmeranda commented on packages/prometheus-federator/charts/Chart.yaml
> +appVersion: 0.3.5
Oh ok sick

2023-12-15 16:36 UTC, alexandreLamarre commented on packages/prometheus-federator/charts/values.yaml
> +    tag: v0.3.5
Taking a look at past PRs, we are expected to tag the merge commit as the release version, CI runs with the a local $TAG option

2023-12-15 17:09 UTC, joshmeranda approved these changes

2023-12-15 17:14 UTC, merged