[main][2/2] Repo reorg Combine
rancher/prometheus-federator pull request #97
Opened 2024-10-10 22:22 UTC by mallardduck

A follow up to and considered blocked by: https://github.com/rancher/prometheus-federator/pull/96

This PR will actually combine things together and will be rebased on `[mallardduck:repo-reorg/prepare](https://github.com/mallardduck/prometheus-federator/tree/repo-reorg/prepare)` until 96 is merged - and which time it can be easily rebased on`main` and the PR will look smaller. Until then it will stay a draft.

2024-10-14 14:53 UTC, mallardduck commented
@joshmeranda / @jbiers - I think this is ready for review now. I plan to send a follow up PR that handles setting up release artifacts for all 3 of the command entry points. Essentially the same stuff I implemented in helm-project-operator for the first 2 when they were merged - but ported to this repo.

However since this PR is pretty large already, I don't want that work to hold up this phase of things. Especially since all 3 being merged into one repo means those artifacts aren't necessary for building `prometheus-federator` at all anymore.

2024-10-14 18:31 UTC, joshmeranda requested changes

2024-10-14 18:31 UTC, joshmeranda commented on packages/helm-locker/charts/values.yaml
> +  tag: head
This needs to be a specific version, we can't ship charts that aren't pinned to an image version (going through the commits forgive me if you fix this in a later commit)

2024-10-14 18:31 UTC, joshmeranda commented on charts/helm-locker/0.0.2/values.yaml
> +  tag: head
same deal as above

2024-10-14 18:31 UTC, joshmeranda commented on charts/project-operator-example/0.0.0/Chart.yaml
These examples should not be in the `charts` directory. They should stored under the `examples/`

2024-10-14 19:00 UTC, mallardduck commented on packages/helm-locker/charts/values.yaml
> +  tag: head
I didn't think we need to consider these published charts as they're documented as not for individual use.

Maybe I should just mark this package as `doNotRelease` like the `helm-project-operator` chart is and modify any CI that uses this chart to just pull from the `packages/` dir?

2024-10-14 19:01 UTC, mallardduck commented on charts/project-operator-example/0.0.0/Chart.yaml
Yeah - think that was solved in latter commits.

2024-10-16 18:36 UTC, jbiers approved these changes

2024-10-16 21:25 UTC, joshmeranda approved these changes

2024-10-17 17:06 UTC, merged